/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test_gradle;

import org.junit.Test;
import test_gradle.implementations.Client;
import test_gradle.implementations.Server;
import test_gradle.interfaces.CallbackClient;
import test_gradle.interfaces.CallbackServer;


public class AppTest {

    private static final String IP = "localhost";
    private static final int PORT = 9999;

    @Test
    public void testCLientServer() throws InterruptedException{

        new Thread(() ->
                    new Server<>(new Coder(), IP, PORT, new CallbackServer<>() {

                    @Override
                    public String callingback(String message) {
                        return message + " echo from Server";
                    }
                })).start();


        Client<String> client = new Client<>(new Coder(), new CallbackClient<>() {
            @Override
            public void callingback(String message) {
                System.out.println("got message: " + message);
            }
        });
        client.connect("localhost", PORT);

        String[] messages = {"Hello", "How are you?", "Good bye!"};
        for(String message : messages) {
            client.send(message);
            Thread.sleep(75);
        }
    }
}
