/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.studing.nio;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import org.studing.nio.factories.CallbackFactory;
import org.studing.nio.factories.DecoderFactory;
import org.studing.nio.implementations.Coder;
import org.studing.nio.implementations.Server;
import org.studing.nio.implementations.callbacks.MyCallbackClient;
import org.studing.nio.implementations.clients.Client;
import org.studing.nio.implementations.factories.MyCallbackFactory;
import org.studing.nio.implementations.factories.MyDecoderFactory;
import org.studing.nio.interfaces.IClient;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.TimeUnit;


public class AppTest {

    private static final String IP = "localhost";
    private static int port = 8080;
    private static Server<String> server;
    private static Client<String> client;
    private static MyCallbackClient<String> callbackClient;

    private static List<IClient<String>> clients;
    private static BlockingQueue<String> messages;


    private static final Logger log = LogManager.getLogger(AppTest.class);

    @Before
    public void initialisation() throws Exception{
        System.setProperty("log4j.configurationFile","log4j2.properties");

        clients = new ArrayList<>();
        messages = new ArrayBlockingQueue<>(3);
        DecoderFactory<String> decoderFactory = new MyDecoderFactory();
        CallbackFactory<String> callbackFactory = new MyCallbackFactory<>(clients, messages);

        callbackClient = new MyCallbackClient<>();
        client = new Client<>(new Coder(), callbackClient);

        server = new Server<>(IP, port, decoderFactory, callbackFactory);
    }

    @After
    public void terminate() throws Exception{
        server.close();
        client.close();
        port++;
    }


    @Test
    public void testSendingFromServer() throws Exception {

        server.start();

        client.connect(IP, port);
        client.start();

        Thread.sleep(75);
        String message = "Welcome!";
        clients.get(0).send(message);

        String messageReceived = callbackClient.poll();

        assertEquals(message, messageReceived);
    }


    @Test
    public void testSendingFromClient() throws Exception {
        server.start();

        client.connect(IP, port);
        client.start();

        String message = "Welcome!";
        Thread.sleep(50);
        client.send(message);

        String messageReceived = messages.poll(3, TimeUnit.SECONDS);

        assertEquals(message, messageReceived);
    }
}
